### PR TITLE
get underlying observable if knockout-es5

### PR DESCRIPTION
**Pull request by jrsearles**
fixes issue #16 

add support for knockout-es5

### CODE REVIEW

**Comment by ZiadJ** [comment]
Wouldn't it be better not to use a function for that since it's not being used elsewhere and only takes up two lines of code? It would also be good to comment it so we know it is a knockout-es5 specific functionality.

**Comment by jrsearles** [comment]
Sure - i can make that change. I thought this would be more readable, but either way is fine.

Thinking about this more though i was wondering if it might be better to instead expose a "getter" function as an option. That way a user can supply their own method to retrieve the observable and you wouldn't have to "know" about other plugins.

Let me know if you'd rather go that route and i can make that change. Otherwise i'll tweak this and resubmit.

Thanks!

**Comment by ZiadJ** [comment]
Totally agree! This could have other uses as well, like ignoring a certain node if a false value is returned. So that would be the way to go. I suggest you target the beta version though since I'm about to phase out the older version.

**Comment by jrsearles** [comment]
Alright - sounds good. I'll close this PR and submit another shortly.

**Pull request closed without merging**
